/* Generated by scripts/build-tokens.mjs — do not edit */

export const detectionSeverities = ["critical","high","medium","low"] as const
export const detectionStatuses = ["open","acked","rejected"] as const
export const appThemes = ["dark","light","high-contrast"] as const
export const appDensities = ["comfortable","compact"] as const

export type TokenSeverity = (typeof detectionSeverities)[number]
export type TokenStatus = (typeof detectionStatuses)[number]
export type TokenTheme = (typeof appThemes)[number]
export type TokenDensity = (typeof appDensities)[number]

export const severityShortLabels: Record<TokenSeverity, string> = {
  critical: 'CRIT',
  high: 'HIGH',
  medium: 'MED',
  low: 'LOW',
}

export const staleThresholdMs = 5 * 60 * 1000
