import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const tokensDir = path.join(rootDir, 'tokens')
const stylesDir = path.join(rootDir, 'src', 'styles')

function readJson(relativePath) {
  return JSON.parse(fs.readFileSync(path.join(tokensDir, relativePath), 'utf8'))
}

function flattenDtcg(node, prefix = '') {
  const result = {}
  for (const [key, value] of Object.entries(node)) {
    if (key.startsWith('$')) {
      continue
    }
    const nextKey = prefix ? `${prefix}-${key}` : key
    if (value && typeof value === 'object' && '$value' in value) {
      result[nextKey] = value.$value
    } else if (value && typeof value === 'object') {
      Object.assign(result, flattenDtcg(value, nextKey))
    }
  }
  return result
}

function toCssBlock(selector, vars) {
  const lines = Object.entries(vars)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, value]) => `  --${name}: ${value};`)
  return `${selector} {\n${lines.join('\n')}\n}`
}

function buildCss() {
  const primitive = flattenDtcg(readJson('primitive/space.json'))
  Object.assign(primitive, flattenDtcg(readJson('primitive/font.json')))
  Object.assign(primitive, flattenDtcg(readJson('primitive/radius.json')))
  Object.assign(primitive, flattenDtcg(readJson('primitive/shadow.json')))

  const themes = {
    dark: flattenDtcg(readJson('semantic/dark.json')),
    light: flattenDtcg(readJson('semantic/light.json')),
    'high-contrast': flattenDtcg(readJson('semantic/high-contrast.json')),
  }

  const densities = {
    comfortable: flattenDtcg(readJson('density/comfortable.json')),
    compact: flattenDtcg(readJson('density/compact.json')),
  }

  const blocks = [
    '/* Generated by scripts/build-tokens.mjs — do not edit */',
    toCssBlock(':root', primitive),
    toCssBlock(":root,\n:root[data-theme='dark']", themes.dark),
    toCssBlock(":root[data-theme='light']", themes.light),
    toCssBlock(":root[data-theme='high-contrast']", themes['high-contrast']),
    toCssBlock(":root,\n:root[data-density='comfortable']", densities.comfortable),
    toCssBlock(":root[data-density='compact']", densities.compact),
  ]

  return `${blocks.join('\n\n')}\n`
}

function buildTs() {
  const severities = ['critical', 'high', 'medium', 'low']
  const statuses = ['open', 'acked', 'rejected']
  const themes = ['dark', 'light', 'high-contrast']
  const densities = ['comfortable', 'compact']

  return `/* Generated by scripts/build-tokens.mjs — do not edit */

export const detectionSeverities = ${JSON.stringify(severities)} as const
export const detectionStatuses = ${JSON.stringify(statuses)} as const
export const appThemes = ${JSON.stringify(themes)} as const
export const appDensities = ${JSON.stringify(densities)} as const

export type TokenSeverity = (typeof detectionSeverities)[number]
export type TokenStatus = (typeof detectionStatuses)[number]
export type TokenTheme = (typeof appThemes)[number]
export type TokenDensity = (typeof appDensities)[number]

export const severityShortLabels: Record<TokenSeverity, string> = {
  critical: 'CRIT',
  high: 'HIGH',
  medium: 'MED',
  low: 'LOW',
}

export const staleThresholdMs = 5 * 60 * 1000
`
}

function main() {
  fs.mkdirSync(stylesDir, { recursive: true })
  fs.writeFileSync(path.join(stylesDir, 'tokens.css'), buildCss())
  fs.writeFileSync(path.join(stylesDir, 'tokens.ts'), buildTs())
  console.log('Built src/styles/tokens.css and src/styles/tokens.ts')
}

main()
